package View;

/**
 *
 * @author Daniel
 */
public class RegistroView extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public RegistroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCreaTuCuenta = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNick = new javax.swing.JLabel();
        sepNombre = new javax.swing.JSeparator();
        txtApellido = new javax.swing.JTextField();
        sepApellido = new javax.swing.JSeparator();
        lblNombre1 = new javax.swing.JLabel();
        txtNick = new javax.swing.JTextField();
        sepNick = new javax.swing.JSeparator();
        lblEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        sepEdad = new javax.swing.JSeparator();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        sepCorreo = new javax.swing.JSeparator();
        lblPassword = new javax.swing.JLabel();
        sepPassword = new javax.swing.JSeparator();
        btnRegistrarse = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crea tu cuenta");
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCreaTuCuenta.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblCreaTuCuenta.setForeground(new java.awt.Color(255, 255, 255));
        lblCreaTuCuenta.setText("Crea tu cuenta");
        jPanel1.add(lblCreaTuCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblApellido.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(255, 255, 255));
        lblApellido.setText("Apellido:");
        jPanel1.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        txtNombre.setBackground(new java.awt.Color(0, 0, 0));
        txtNombre.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(null);
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 130, 20));

        lblNick.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblNick.setForeground(new java.awt.Color(255, 255, 255));
        lblNick.setText("Nick:");
        jPanel1.add(lblNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 80, -1));
        jPanel1.add(sepNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, 2));

        txtApellido.setBackground(new java.awt.Color(0, 0, 0));
        txtApellido.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtApellido.setBorder(null);
        txtApellido.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 130, 20));
        jPanel1.add(sepApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 130, 2));

        lblNombre1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre1.setText("Nombre:");
        jPanel1.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtNick.setBackground(new java.awt.Color(0, 0, 0));
        txtNick.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        txtNick.setForeground(new java.awt.Color(255, 255, 255));
        txtNick.setBorder(null);
        txtNick.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 170, 20));
        jPanel1.add(sepNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 170, 2));

        lblEdad.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblEdad.setForeground(new java.awt.Color(255, 255, 255));
        lblEdad.setText("Edad:");
        jPanel1.add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        txtEdad.setBackground(new java.awt.Color(0, 0, 0));
        txtEdad.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        txtEdad.setForeground(new java.awt.Color(255, 255, 255));
        txtEdad.setBorder(null);
        txtEdad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 90, 20));
        jPanel1.add(sepEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 90, 2));

        lblCorreo.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("Correo Electronico:");
        jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 130, -1));

        txtCorreo.setBackground(new java.awt.Color(0, 0, 0));
        txtCorreo.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setBorder(null);
        txtCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 290, 20));
        jPanel1.add(sepCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 290, 2));

        lblPassword.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Contraseña:");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 130, -1));
        jPanel1.add(sepPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 290, 2));

        btnRegistrarse.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarse.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.setBorder(null);
        btnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 90, 30));

        txtPassword.setBackground(new java.awt.Color(0, 0, 0));
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 290, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegistrarse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCreaTuCuenta;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNick;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JSeparator sepApellido;
    private javax.swing.JSeparator sepCorreo;
    private javax.swing.JSeparator sepEdad;
    private javax.swing.JSeparator sepNick;
    private javax.swing.JSeparator sepNombre;
    private javax.swing.JSeparator sepPassword;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtEdad;
    public javax.swing.JTextField txtNick;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
